name: CI
on:
  push:
    branches:
      - master
      - next
      - 'releases/**'

env:
  CI: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [ 1.12.x, 1.13.x ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      # Cannot use make here; version too old on macos.
      - run: go test ./...
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: 1.13.x
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: go get honnef.co/go/tools/cmd/staticcheck
      - run: make check
